ci: Extract swift compiler errors to bottom of log

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -30,7 +30,15 @@ workflows:
             ENTITLEMENTS_ALLOWED=NO \
             ARCHIVE=YES \
             generate_infoplist_file=YES \
-            COMPILER_INDEX_STORE_ENABLE=NO
+            COMPILER_INDEX_STORE_ENABLE=NO | tee build.log
+
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            echo "========================================"
+            echo "💥 EXTRACTED SWIFT ERRORS:"
+            echo "========================================"
+            grep -C 5 "error:" build.log
+            exit 1
+          fi
             
       - name: Build IPA
         script: |
